/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconMdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    IconMdiBookshelf: typeof import('~icons/mdi/bookshelf')['default']
    IconMdiCheck: typeof import('~icons/mdi/check')['default']
    IconMdiCheckCircle: typeof import('~icons/mdi/check-circle')['default']
    IconMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IconMdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    IconMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IconMdiChevronUp: typeof import('~icons/mdi/chevron-up')['default']
    IconMdiCircleOutline: typeof import('~icons/mdi/circle-outline')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiCogOutline: typeof import('~icons/mdi/cog-outline')['default']
    IconMdiDeleteOutline: typeof import('~icons/mdi/delete-outline')['default']
    IconMdiFormatListBulleted: typeof import('~icons/mdi/format-list-bulleted')['default']
    IconMdiHelpCircleOutline: typeof import('~icons/mdi/help-circle-outline')['default']
    IconMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IconMdiPlaylistEdit: typeof import('~icons/mdi/playlist-edit')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
